import * as fs from "node:fs/promises";
import * as path from "node:path";
import { logger } from "@/server/logger";
import { resolveHostPath } from "@/server/projects/hostPaths";
import { getTailscaleConfig } from "./config";

/**
 * Generate a Tailscale Serve config JSON for auto-HTTPS.
 * Maps HTTPS 443 → localhost:localPort inside the container.
 */
function buildServeConfig(localPort: number): string {
	return JSON.stringify(
		{
			TCP: { "443": { HTTPS: true } },
			Web: {
				"${TS_CERT_DOMAIN}:443": {
					Handlers: { "/": { Proxy: `http://127.0.0.1:${localPort}` } },
				},
			},
		},
		null,
		2,
	);
}

interface InjectOptions {
	projectId: string;
	slug: string;
	/** Path to the directory containing docker-compose.yml */
	composePath: string;
	/** "preview" for dev containers, "production" for prod */
	variant: "preview" | "production";
}

/**
 * Generate a complete Tailscale-enabled compose file for a project.
 *
 * This replaces (not overlays) the original compose file. It duplicates
 * the service definition WITHOUT the `ports:` key and adds the tailscale
 * sidecar with `network_mode: "service:tailscale"`.
 *
 * Returns the filename if written, or null if Tailscale is disabled.
 */
export async function injectTailscaleSidecar(
	options: InjectOptions,
): Promise<string | null> {
	const config = await getTailscaleConfig();
	if (!config.enabled || !config.authKey) {
		return null;
	}

	const hostname =
		options.variant === "preview" ? `${options.slug}-preview` : options.slug;

	const localPort = options.variant === "preview" ? 4321 : 3000;

	// Write serve config directory
	const serveConfigDir = path.join(options.composePath, "ts-serve-config");
	await fs.mkdir(serveConfigDir, { recursive: true });
	await fs.writeFile(
		path.join(serveConfigDir, "serve.json"),
		buildServeConfig(localPort),
	);

	// Translate the container path to a host path so docker daemon (running on
	// the host) can bind-mount the correct directory. Without this, compose
	// would pass `./ts-serve-config` which resolves to a container-only path.
	const serveConfigHostPath = await resolveHostPath(serveConfigDir);

	let composeContent: string;

	if (options.variant === "preview") {
		composeContent = buildPreviewCompose(
			hostname,
			config.authKey,
			options.projectId,
			serveConfigHostPath,
		);
	} else {
		composeContent = buildProductionCompose(
			hostname,
			config.authKey,
			options.projectId,
			serveConfigHostPath,
		);
	}

	const filename = "docker-compose.tailscale.yml";
	await fs.writeFile(path.join(options.composePath, filename), composeContent);

	logger.info(
		{ hostname, variant: options.variant, projectId: options.projectId },
		"Tailscale compose file written",
	);

	return filename;
}

function buildPreviewCompose(
	hostname: string,
	authKey: string,
	projectId: string,
	serveConfigHostPath: string,
): string {
	return `# Auto-generated by doce.dev — Tailscale-enabled preview
# Replaces docker-compose.yml when Tailscale is active.
# Access at https://${hostname}.<tailnet>.ts.net
services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: ${hostname}
    environment:
      - TS_AUTHKEY=${authKey}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_USERSPACE=true
    volumes:
      - ts-state:/var/lib/tailscale
      - ${serveConfigHostPath}:/config:ro
    restart: unless-stopped

  preview:
    build:
      context: .
      dockerfile: Dockerfile.preview
      args:
        PREVIEW_BASE_IMAGE: \${DOCE_PREVIEW_BASE_IMAGE:-node:22-alpine}
    volumes:
      - type: bind
        source: \${PROJECT_PREVIEW_BIND_MOUNT}
        target: /app
      - preview_node_modules:/app/node_modules
      - pnpm-store:/root/.local/share/pnpm/store
    environment:
      - HOST=0.0.0.0
    network_mode: "service:tailscale"
    depends_on:
      - tailscale

volumes:
  ts-state:
    name: doce_ts_${projectId}_preview
  preview_node_modules:
    name: doce_\${PROJECT_ID}_preview_node_modules
  pnpm-store:
    external: true
    name: doce-global-pnpm-store
`;
}

function buildProductionCompose(
	hostname: string,
	authKey: string,
	projectId: string,
	serveConfigHostPath: string,
): string {
	return `# Auto-generated by doce.dev — Tailscale-enabled production
# Replaces docker-compose.production.yml when Tailscale is active.
# Access at https://${hostname}.<tailnet>.ts.net
services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: ${hostname}
    environment:
      - TS_AUTHKEY=${authKey}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_USERSPACE=true
    volumes:
      - ts-state:/var/lib/tailscale
      - ${serveConfigHostPath}:/config:ro
    restart: unless-stopped

  production:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        PRODUCTION_BASE_IMAGE: \${DOCE_PRODUCTION_BASE_IMAGE:-node:22-alpine}
    volumes:
      - doce-global-pnpm-store:/root/.local/share/pnpm/store
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    network_mode: "service:tailscale"
    depends_on:
      - tailscale
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  ts-state:
    name: doce_ts_${projectId}_production
  doce-global-pnpm-store:
    external: true
    name: doce-global-pnpm-store
`;
}

/**
 * Clean up Tailscale sidecar files for a project.
 */
export async function removeTailscaleSidecar(
	composePath: string,
): Promise<void> {
	try {
		await fs.rm(path.join(composePath, "docker-compose.tailscale.yml"), {
			force: true,
		});
		await fs.rm(path.join(composePath, "ts-serve-config"), {
			recursive: true,
			force: true,
		});
	} catch {
		// Ignore cleanup errors
	}
}
