const TRIMMED_EXPR = "$" + "{trimmed.slice(0, MAX_PROMPT_CHARS)}";
const ORIGINAL_PROMPT_EXPR = "$" + "{originalPromptBlock}";

const pluginLines = [
	'import * as fs from "node:fs/promises";',
	'import * as path from "node:path";',
	"",
	'const PROJECT_PROMPT_PATH = path.join(".doce", "project-prompt.md");',
	"const MAX_PROMPT_CHARS = 12_000;",
	"",
	"async function readOriginalPrompt(directory) {",
	"\ttry {",
	"\t\tconst filePath = path.join(directory, PROJECT_PROMPT_PATH);",
	'\t\tconst content = await fs.readFile(filePath, "utf-8");',
	"\t\tconst trimmed = content.trim();",
	"\t\tif (!trimmed) {",
	"\t\t\treturn null;",
	"\t\t}",
	"",
	"\t\tif (trimmed.length <= MAX_PROMPT_CHARS) {",
	"\t\t\treturn trimmed;",
	"\t\t}",
	"",
	`\t\treturn \`${TRIMMED_EXPR}\\n\\n[truncated for compaction]\`;`,
	"\t} catch {",
	"\t\treturn null;",
	"\t}",
	"}",
	"",
	"function buildCompactionContext(originalPrompt) {",
	"\tconst originalPromptBlock = originalPrompt",
	"\t\t? originalPrompt",
	'\t\t: "Original project prompt unavailable. Infer the project goal from the most durable signals in the session and codebase.";',
	"",
	"\treturn `## doce.dev Project Anchor",
	"",
	"You are compacting a long-running doce.dev build session.",
	"Preserve the project's identity, implementation momentum, and the user's original intent.",
	"",
	"### Original Project Prompt",
	ORIGINAL_PROMPT_EXPR,
	"",
	"### Preserve through compaction",
	"- the core goal of the project",
	"- explicit requirements and constraints",
	"- what has already been implemented",
	"- the current implementation status",
	"- the key technical and product decisions made",
	"- the most important files and code areas involved",
	"- known issues, blockers, or unfinished work",
	"- the immediate next step",
	"",
	"### Journey summary requirements",
	"When summarizing the journey so far:",
	"- preserve decisions, implementation state, and next actions over raw logs",
	"- mention abandoned approaches only if they still matter",
	"- prefer the solution currently reflected in the codebase",
	"- keep the continuation implementation-oriented and specific",
	"",
	"### Preferred continuation structure",
	"## Project Goal",
	"- ...",
	"",
	"## Constraints",
	"- ...",
	"",
	"## Progress So Far",
	"- ...",
	"",
	"## Key Decisions",
	"- ...",
	"",
	"## Important Files",
	"- ...",
	"",
	"## Known Issues / Risks",
	"- ...",
	"",
	"## Next Step",
	"- ...`;",
	"}",
	"",
	"export const DoceCompactionPlugin = async ({ directory }) => {",
	"\treturn {",
	'\t\t"experimental.session.compacting": async (_input, output) => {',
	"\t\t\tconst originalPrompt = await readOriginalPrompt(directory);",
	"\t\t\toutput.context.push(buildCompactionContext(originalPrompt));",
	"\t\t},",
	"\t};",
	"};",
] as const;

export const DOCE_COMPACTION_PLUGIN_SOURCE = `${pluginLines.join("\n")}\n`;
