FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

EXPOSE 4321

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .

RUN mkdir -p /app/data

HEALTHCHECK --interval=5s --timeout=5s --retries=10 --start-period=30s \
    CMD wget --no-verbose --tries=1 --spider http://localhost:4321 || exit 1

CMD ["pnpm", "dev"]
